src/components/Lesson.js
src/components/NavBar.js

Un-capitalize PropTypes

---

README.md
src/index.js

Download [Chrome Extension here](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).

Redux DevTools

---

.travis.yml
package.json
travis_build_prod.sh

Create shell script to check if build is completed without error.
Build without --progress

Add production build script to Travis

---

webpack.base.config.babel.js

Quick fix for Windows removing path related errors. Not a long term solution.

Windows quick fix.

---

.bootstraprc

Enable some bootstrap components: 
Mixins,  scaffolding, grid,  animations, dropdown, utilities and responsive-utilities

Bootstrap components

---

src/assets/css/_colors.scss
src/components/CourseList/CourseItem.js
src/components/CourseList/CourseItem.scss
src/components/CourseList/CourseList.js
src/components/CourseList/CourseList.scss

Style CourseList component

---

.bootstraprc
src/pages/FrontPage.js

Erstatt gammeldags bootstrap med react-bootstrap

React-bootstrap on FrontPage

---

src/index-template.ejs

Add viewport meta tag to index template for mobile scaling.

Viewport meta tag

---

README.md

[open](https://www.npmjs.com/package/open) is also an option..

readme: add host and port to instructions

---

src/components/LessonList/LessonItem.js
src/components/LessonList/LessonItem.scss

This PR is related to external links in #4.
Also replaces temporary font awesome with temporary bootstrap glyphicons in PlaylistPage, which is related to #62.

Use external links to external lessons

---

src/components/LessonList/LessonItem.js

To avoid getting unwanted styling from navigation links

Use Link instead of NavLink in LessonItem

---

src/components/Filter/LessonFilter.js
src/components/PlaylistPage/MobileComponents.js
src/pages/FrontPage.js
src/pages/PlaylistPage.js

Wrap LessonFilter in a container

---

src/assets/css/_buttons.scss
src/assets/css/app.scss

Create bootstrap button classes for student & teacher

---

.stylelintrc
.travis.yml
package.json
src/assets/css/_buttons.scss
src/assets/css/_colors.scss
src/assets/css/_nav.scss
src/assets/css/_panels.scss
src/components/ButtonItem.scss
src/components/Filter/FilterGroup.scss
src/components/LessonList/LessonItem.scss
src/components/Navigation/FlagGroup.scss
src/pages/FrontPage.scss

Also made changes to all the scss-files that had mistakes according to the linter.

Add stylelint to check all scss files, and add to travis.

---

src/selectors/course.js
src/selectors/lesson.js
src/util.js
test/util_spec.js

Filter by union of items in same group, intersection between groups.
Also fixes a bug where some tags in filter were removed instead of merged correctly.

Modify filter logic

---

src/components/CourseList/CourseItem.js
src/components/LessonList/LessonItem.js

And change 'new-window' icon on LessonItems

Open external courses in new tab

---

src/pages/PlaylistPage.js
src/pages/PlaylistPage.scss

Fix position of filter, levelNavigation and playlists on PlaylistPage

---

.bootstraprc
src/assets/css/_type.scss
src/assets/css/app.scss
src/components/Navigation/ModeIndicator.js
src/components/Navigation/ModeIndicator.scss
src/components/Navigation/NavBar.js

Forsøk på å gjøre det tydeligere hvilken `mode(student/teacher)` man er i.
Er det andre måter vi også/heller kan tydeliggjøre dette bedre på?

Text under NavBar to tell if state is in student or teacher mode

---

package.json
webpack.base.config.babel.js

Implements a solution for Windows where backslashes are stripped from the path.

Fix Windows path issue.

---

src/store.js
src/util.js

Course tags will be overridden by lesson tags.
Related to #123

Lessons inherit tags from course

---

.bootstraprc
README.md
package.json
src/assets/css/_highlight.scss
src/assets/css/_type.scss
src/assets/css/app.scss
src/components/Lesson/Lesson.js
src/highlighting.js
webpack.base.config.babel.js

commit 183c2bd45aa568c637d4753fdf33202397fc87d5
Author: Lance Olav Eastgate <lanceolav@lanceolav.com>
Date:   Mon Aug 1 23:52:06 2016 +0200
Add noParse for scratchblocks to avoid warning.
commit ccf8d4dfe4a4430e645e9cbd20bccee590149f34
Merge: 1f9302a 599956c
Author: Lance Olav Eastgate <lanceolav@lanceolav.com>
Date:   Mon Aug 1 20:02:41 2016 +0200
Merge branch 'highlight' of https://github.com/arve0/codeclub-viewer into arve0-highlight
commit 599956cdc4d83837440cb893afea9ce2ce95fbe1
Author: arve0 <arve.seljebu@gmail.com>
Date:   Mon Aug 1 00:29:09 2016 +0200
scratchblocks: fix client-side detecting, fix HTML-minification
client-side: use `document`
HTML-minification:
- use <pre class=blocks> for both dev and production
- detect both <code class="b"> and <code class=b>
commit …

PR70 squashed (scratchblocks / highlight)

---

src/pages/FrontPage.js

Implements #88. Astrokatt is used until someone makes the 'Hello World' exercise.

Add link to getting-started exercise.

---

npm-shrinkwrap.json
src/components/Lesson/Lesson.js
src/components/Lesson/Lesson.scss

Set max width on lesson page.

---

src/components/Filter/ActiveFilterItem.js
src/components/Filter/ActiveFilterItem.scss
src/components/FrontPage/Filter.js

Solves #119.
Creates a new ActiveFilterItem component which displays all current active FilterItems on a mobile view. Also comes with a handy remove function which allows you to remove active filters without opening the entire filter menu.

119 activefilteritem

---

src/components/PlaylistPage/LessonItem.js
src/components/PlaylistPage/LessonList.js
src/components/PlaylistPage/PlaylistNavigation.js

Issue #221 
Removes all mock constraints code.

Removes mock constraints from code

---

src/components/CourseList/CourseItem.js

Issue229 crawlable links

---

src/util.js

Changed getLevelName() to be used with level-confg.json file in "oppgaver"-repo

---

src/components/FrontPage/TeacherInfobox.js

This completes the info text which has been added in [PR #373 in oppgaver](https://github.com/kodeklubben/oppgaver/pull/373).

Add relevant link description which correspond to nicer info box text

---

.stylelintrc
src/components/Lesson/Content.scss
src/styles/pre-customizations.scss
webpack.base.config.babel.js

Løser problemet beskrevet i issue #240.
Den får også med noen endringer på bootstrap som ikke var tatt med tidligere (inkludert tabell-farge).

Issue240: Add code to render tables like in codeclub_lesson_builder

---

src/pages/PlaylistPage.js
src/selectors/lesson.js
test/selectors/lesson_spec.js

Clean up playlistpage, move getLessonsByLevel-logic to selector, add test.

Rydde litt i playlistpage

---

src/components/Lesson/Content.scss

The circles were first implemented in PR #248 
The same adjustments might be smart to do in https://github.com/arve0/codeclub_lesson_builder/pull/230

Slight adjustment of the vertical alignment of the circles for the lists

---

src/components/CourseList/CourseItem.js
src/components/Navigation/NavLink.js
src/index-static.js
src/index.js
src/pages/PageNotFound.js
src/routeObject.js

See https://github.com/ReactTraining/react-router/blob/v2.8.1/docs/guides/MinimizingBundleSize.md

Import stuff from react-router/lib to decrease code size

---

src/localStorage.js

Issue 245: Fix storing to localstorage so that if it fails (e.g. during server side rendering), it does so silently.

Let localstorage fail silently

---

src/components/CourseList/CourseItem.scss

Small fix for hover on courseitem

---

src/components/FrontPage/Filter.js
src/pages/PlaylistPage.js

fix filter on playlistpage

---

src/action_creators.js
src/components/FrontPage/WelcomeBox.js
src/components/Lesson/Lesson.js
src/index.js
src/localStorage.js
src/polyfills.js
src/reducer.js
src/reducers/checkboxes.js
src/reducers/language.js
src/reducers/mode.js
src/reducers/welcomeBox.js
src/store.js
src/util.js

Adds checkboxes to state and localStorage with the function onclickAndSetCheckboxes.
When visiting a new lesson it stores the path and an empty object in state and localstorage, if there was no object of this lesson in localstorage from before. If there was and object from before it adds an checked atribute to those checkboxes that is set to true in localstorage
When checking a checkbox, it imports every checkbox in that lesson to an object and sets the checkbox that is checked to true.
Right now there is one bug. The function creates a new object every time you check a checkbox. Try to check some checkboxes, reload lesson, check som new checboxes, reload lesson. Now there is only the latest checked checkboxes

269 checkboxfunction

---

src/constants/captions_nn.js

Omsett captions_nn.js til nynorsk

---

src/components/PlaylistPage/LessonItem.js
src/components/PlaylistPage/LessonItem.scss
src/util.js

Solves #150. 
Right now it only shows introductiontext when hover. If figure is available then it should show that too. And then style it. Maybe set max length of introductiontext? And max width for picture?

Issue 150 lessoninfo

---

src/components/PlaylistPage/LessonItem.js

Issue 310-externalGlyph

---

src/pages/PlaylistPage.js

Filter on playlistpage in mobilemode

---

src/components/Lesson/ImprovePage.js
src/components/Lesson/ImprovePage.scss
src/constants/captions_da.js
src/constants/captions_en.js
src/constants/captions_hr.js
src/constants/captions_nb.js
src/constants/captions_nn.js
src/constants/captions_sv.js

Add new button with link to forum, fixed some of the styling and added target="_blank" to buttons

Add forumbutton to improvepagebox

---

src/components/Navigation/BreadCrumb.js

Added levelicon breadcrumbs for README files too

Levelicon in navbar

---

src/util.js

Removed > from regex in case there is more attributes to <a>

Regex for target blank

---

src/components/Filter/FilterGroup.js
src/components/Filter/FilterGroup.scss

Issue 317 collapse on filtergroups

---

src/components/Lesson/Lesson.js

HTMLCollection to array

---

src/components/FrontPage/Filter.js
src/components/PlaylistPage/LessonItem.scss
src/components/PlaylistPage/LessonList.js
src/components/PlaylistPage/LessonList.scss
src/components/PlaylistPage/PlaylistNavigation.js
src/pages/PlaylistPage.js
src/pages/PlaylistPage.scss

Better margins for lessonlist. Same width as everything else on playlistpage. 
Better margin for courseinfobutton

Small marginfixes 

---

src/components/Navigation/BreadCrumb.js
src/components/Navigation/BreadCrumb.scss
src/components/Navigation/LanguageDropdown.js
src/components/Navigation/LanguageDropdown.scss
src/components/Navigation/NavBar.scss

Added coursename to navbar and removed language name in language dropdown in mobilemode

Better navbar for mobile

---

src/components/PlaylistPage/PlaylistNavigation.js

Issue 342 hide playlist with zero lessons

---

src/components/PlaylistPage/LevelNavigation.js
src/components/PlaylistPage/LevelNavigation.scss
src/pages/PlaylistPage.js
src/pages/PlaylistPage.scss

Solves #260
This is at least working on every browser!
Commented out "jump to" from mobile mode. This didn't work before and do not work with the new solution either...

Issue 260 jump to lesson index

---

test-links.js

Fixed eslint for test-links.js

---

src/components/Lesson/Lesson.js
src/components/MarkdownRenderer.js
yarn.lock

Should solve issue #257, and replaces PR #324.

Add MarkdownRenderer, and use it for Author in Lesson.

---

src/components/CourseList/CourseItem.scss

Bugfix when [this](https://github.com/kodeklubben/oppgaver/pull/541) gets merged

Support for longer names for external courses

---

src/constants/captions_en.js

Did have a caption for forumbutton

Missing caption in en

---

src/constants/captions_da.js
src/constants/captions_nb.js
src/constants/captions_nn.js
src/constants/captions_sv.js

Changed caption for science

---

package.json

Stylelint for windows

---

src/components/Lesson/Lesson.js
src/constants/captions_da.js
src/constants/captions_en.js
src/constants/captions_nb.js
src/constants/captions_nn.js
src/constants/captions_sv.js

Solves #351 
Checks if there is a link and a translator

Issue 351-translatedby

---

src/components/CollapsiblePanel.js
src/components/CourseList/CourseItem.js
src/components/CourseList/CourseItem.scss
src/components/PlaylistPage/LessonItem.js
src/components/PlaylistPage/LessonItem.scss
src/components/TooltipComponent.js
src/components/TooltipComponent.scss

Use same function as before for lessons.
Need [this](https://github.com/kodeklubben/oppgaver/pull/582) branch to check or be merged from oppgaverepo

Fix hover for courseitem

---

src/util.js

No need for this yet. Nothing is translated and we don't have one lesson in those language

Commented out da and sv

---

package.json
src/routes.js
webpack.base.config.babel.js
webpack.config.babel.js
webpack.static.config.babel.js
yarn.lock

An alternative to PR #388, but using copy-webpack-plugin.
Also cleaned up the dist-folder.

Clean up dist-folder, and add copy-webpack-plugin

---

src/selectors/playlist.js
webpack.base.config.babel.js

Add exclude for playlists and fixed split for playlistcontext

Fix for playlistcollection

---

src/components/Navigation/NavBar.js

Think that came from the cleaning PR...

Removed semicolon from navbar

---

src/components/PlaylistPage/PlaylistNavigation.js

Check to only show collections in nb language

Temporary check for playlist collection

---

webpack.static.config.babel.js

To make yarn buildstatic work on windows too

Buildstatic for windows

---

src/util.js

Issue 349 indexed: false lessons not in filter

---

src/components/Lesson/Content.scss
src/components/Lesson/ImprovePage.scss
src/components/Lesson/Lesson.js
src/components/Lesson/Lesson.scss
src/components/Lesson/LessonButton.js
src/components/Lesson/LessonButton.scss
src/components/Lesson/PrintButton.js
src/components/Lesson/PrintButton.scss
src/components/Lesson/ReadmeButton.js
src/components/Lesson/ReadmeButton.scss
src/components/Lesson/ResetButton.js
src/components/Lesson/ResetButton.scss
src/components/Navigation/Footer.scss
src/constants/captions_da.js
src/constants/captions_en.js
src/constants/captions_nb.js
src/constants/captions_nn.js
src/constants/captions_sv.js
src/processContent.js
src/selectors/frontmatter.js
webpack.base.config.babel.js

A button for window.print()
Could it be done that easily?

PrintButton

---

src/selectors/lesson.js
src/selectors/playlist.js

Solves #365 
Use getFilter instead of getFilteredAndIndexedLessons

Issue 365 Playlists independent of filter

---

src/components/PlaylistPage/LevelNavigation.js
src/pages/PlaylistPage.js
src/pages/PlaylistPage.scss

Mobilemode is like before
Playlist and coursinfo are moved into the header

Rearranged playlists on playlistpage

---

package.json
src/components/PlaylistPage/LevelNavigation.js
src/pages/PlaylistPage.js
src/pages/PlaylistPage.scss
yarn.lock

Fixed playlistpage for courses without playlists and made the jumpTo use AutoAffix
The solution is maybe a bit hard to read now...

JumpTo uses AutoAffix

---

.eslintrc
src/processContent.js
src/util.js
test/util_spec.js

Solves issue #392 
Add path to lesson in img src in tooltip, and added functions basename and dirname (with unittests) in utils. Also loosened string requirements in eslint.

392 fix lesson tooltip picture

---

createLessonPdfs.js

The PR that added PDFs forgot to add the optional subfolder, e.g. beta. This PR includes it.

Let pdfs be saved the the correct subfolder (even with beta)

---

createLessonPdfs.js

Add publicPath to urlbase when rendering pdfs.

Add publicpath to base url when rendering pdfs.

---

pathlists.js
src/components/Lesson/Lesson.js
src/pages/App.js
src/polyfills.js
src/processContent.js
src/reducers/language.js
src/routeObject.js
src/util.js

Solves issue #423 
Add polyfills for Array.prototype.includes and String.prototype.includes, and use them throughout the code.

Add polyfills for Array.prototype.includes and String.prototype.includes

---

createLessonPdfs.js

Checks yarn version (must be greater than 0.28.0 so that it forwards SIGTERM, see https://github.com/yarnpkg/yarn/pull/3789, but have set it here to be at least 1.3.2)
Also added better error handling in createLessonPdfs, and converts now 10 and 10 pdfs at a time.

Check yarn version

---

src/util.js
webpack.base.config.babel.js

Think this solves the problem with the picture in the popover at https://skagevang.github.io/beta/

Add publicpath

---

src/components/PlaylistPage/LessonItem.js
src/components/PlaylistPage/LessonItem.scss

Solves some of #282 
Added a flag to lessonitems, if the GUI language is not the only one checked in the filter. 
Maybe remove filterLanguage[language] from the if statement?
Think this issue should be discussed again, because of the MainLanguageButton, and then this PR is enough.

Issue 282 added flag

---

src/components/Navigation/Footer.js
src/components/Navigation/Footer.scss

Forslag til endring av styling i footer.

A few suggested changes to the footer

---

src/components/Filter/LessonFilter.js
src/constants/captions_da.js
src/constants/captions_nb.js
src/constants/captions_nn.js
src/constants/captions_sv.js
src/pages/PlaylistPage.js
src/selectors/playlist.js

Sjekker om kurset har oppgavesamlinger også

Fix for courses that don't have playlists

---

src/components/Filter/LessonFilter.js
src/components/PopoverComponent.js

Changed the tooltip from bootstrap to the popovercomponent used everywhere else.

Fixed popover for filter info

---

pathlists.js

After upgrading yaml-front-matter, it no longer reads from disk itself. Add fs to do this.

Fix pathlist / PDF

---

src/assets/graphics/flag_nb.svg
src/assets/graphics/flag_nn.svg

Issue 471 different flags for NB and NN

---

src/html-template.ejs
src/index-template.ejs

Solves #482 
Fixed indenting for the files too

Issue 482 add redirect for https

---

src/components/PopoverComponent.js

Solves #498 
Now the filter should expand or collapse if the user clicks on the info about filter

Issue 498 stopPropagation to onClick

---

src/components/LessonPage/MainLanguageButton.js

Issue 527 MainLanguageButton for external lessons fix

---

package.json
yarn.lock

I forked Arve's fork of Scratchblocks and just added nn.json for my fork and other places nynorsk was missing

Use my fork of scratchblocks

---

src/components/LessonPage/PrintInfo.js
src/components/LessonPage/PrintInfo.scss
src/pages/LessonPage.js
src/pages/LessonPage.scss

Issue 531 check if tags exists

---

src/components/Navigation/BreadCrumb.js
src/components/Navigation/ContinueButton.js
src/resources/courseFrontmatter.js

Issue 528 fixed 404 error

---

webpack.config.babel.js

Issue 481 fix internal links for yarn start

---

src/components/FrontPage/TeacherInfobox.js
src/components/FrontPage/TeacherInfobox.scss
src/components/Navigation/Footer.js
src/components/PopoverComponent.js

A page should have a h1, and the next header should be h2 not h3. 
Added roles for the remaining components

Minor accessibility fix

---

src/components/LessonPage/Content.js
src/pages/LessonPage.js
src/reducer.js
src/reducers/hydration.js
src/renderDynamic.js
src/utils/processContent.js
test/reducers/hydration_spec.js
webpack.config.babel.js

Solves #560 and most of #453 (except the links being different for with prefix beta)
Call render only with yarn start, call hydrate otherwise.
Also, only render scratchblocks after hydration.

Only render scratchblocks after hydration.

---

src/components/CourseList/LessonCount.js
src/selectors/course.js
src/selectors/lesson.js
test/selectors/course_spec.js
test/selectors/lesson_spec.js

Sort courses taking all filterlanguages into account

---

src/WithStylesContext.js
src/components/CollapsiblePanel.js
src/components/FrontPage/TeacherInfobox.js
src/components/LessonPage/ToggleButton.js
src/pages/LessonPage.js

Also removed the constructor for the classes that didn't need them

Changed to pure components

---

src/components/CoursePage/LessonItem.js
src/components/InstructionButton.js
src/components/LessonPage/ButtonRow.js
src/components/LessonPage/ImprovePage.js
src/components/LessonPage/MainLanguageButton.js
src/components/LessonPage/PdfButton.js
src/components/Navigation/BreadCrumb.js
src/components/Navigation/ContinueButton.js
src/pages/LessonPage.js
src/resources/lessonContent.js
src/resources/lessonFrontmatter.js
src/store.js

Issue 551 functions for frontmatter

---

package.json
src/components/CollapsiblePanel.js
src/components/CollapsiblePanel.scss
src/components/CourseList/CourseItem.js
src/components/CourseList/CourseItem.scss
src/components/CoursePage/CourseInfo.js
src/components/CoursePage/LessonItem.js
src/components/CoursePage/LessonItem.scss
src/components/CoursePage/LevelNavigation.js
src/components/CoursePage/PlaylistNavigation.js
src/components/CoursePage/PlaylistNavigation.scss
src/components/Filter/FilterItem.js
src/components/Filter/FilterItem.scss
src/components/Filter/LessonFilter.js
src/components/Filter/LessonFilter.scss
src/components/Filter/RadioButtons.js
src/components/InstructionButton.js
src/constants/captions_en.js
src/constants/captions_nb.js
src/constants/captions_nn.js
src/styles/customBootstrapStyles.js
src/styles/mixins.scss
yarn.lock

Solves #158 
What I need to fix before merging is:
Rest is some minor contrast warnings. But we don't care about those for now.

Tabbing to accordion and popovercomponents

---

publish_beta.sh

Change publishBeta-script:
* Remove url-path-prefix
* Build current branch of codeclub-viewer
* Remove CNAME

Change publish_beta.sh to publish from current CCV branch

---

src/store.js

change default state from "playlists" to "all lessons" by setting `defaultPlaylists` to `false`

change default state

---

src/store.js

Warning in console because of the new devTool for Redux will change. 
https://github.com/zalmoxisus/redux-devtools-extension#usage

Fixed warning for redux dev tool

---

src/components/Navigation/LanguageDropdown.js

Since these languages don't need to be changed, there is no need for them to be translated.

Remove translator from LanguageDropdown.js

---

src/html-template.ejs
src/index-template.ejs

Have enforced https for kodeklubben.github.io repo, so hopefully these lines of code could be removed

removed https check

---

src/pages/LessonPage.js
src/utils/checkboxUtils.js

Issue 577 reset checkbox bug

---

package.json
src/html-template.ejs
webpack.config.babel.js
yarn.lock

Read more about it [here](https://developer.mozilla.org/en-US/docs/Web/Manifest)
A PWA (Progressive Web App) needs a manifest and a service worker
This manifest is for norwegian. Maybe it should be in english? The name, shortname and description must be changed then.
For creating a service worker I think we could use [workbox](https://developers.google.com/web/tools/workbox/guides/generate-service-worker/webpack)

Add manifest

---

src/components/CoursePage/PlaylistNavigation.js
src/reducer.js
src/reducers/expandedAccordion.js
src/store.js
test/reducers/expandedAccordion_spec.js

Issue 570 accordions to state and localstorage

---

src/components/LessonPage/ResetButton.js
src/pages/LessonPage.js
src/reducers/checkboxes.js
src/utils/checkboxUtils.js

Make sure checkboxes are updated when content is updated

---

src/utils/processContent.js

Issue 621 scalable blocks

---

src/styles/_fonts.scss

Maybe use swap instead of block?

Add font-display to dyslexic font for better performance

---

src/selectors/course.js

See description and solution suggestion on issue #623

Issue 623: Sort CourseItems consistently

---

.eslintrc
src/reducers/filter.js
src/selectors/filter.js
src/selectors/translate.js
src/utils/processContent.js
test-links.js

Issue 655 Object.prototype rule

---

src/components/LessonPage/PdfButton.js
src/constants/captions_en.js
src/constants/captions_is.js
src/constants/captions_nb.js
src/constants/captions_nn.js

Should be tested in different languages. It's not translated to nynorsk. Maybe the information should be different too.

Add window.confirm to pdf button for more info
