src/components/PlaylistPage/MobileButtonsRow.js
src/components/PlaylistPage/MobileComponents.js

Always show level navigation on mobile if there are enough lessons and more than one level.

Remove LevelNavigation toggle on mobile in PlaylistPage

---

src/components/CourseList/CourseItem.scss
src/components/CourseList/CourseList.js
src/components/CourseList/CourseList.scss
src/components/FrontPage/Courses.js
src/pages/FrontPage.js

Gjøre ikoner og tekst til kursene større på forsiden.
Kurslisten bruker ikke hele bredden på store skjermer.

Increase courseItem size on FrontPage

---

src/components/Lesson/Lesson.js
src/util.js
test/util_spec.js

Fixes issue #212 ads a function to utils that uses a regex to remove the .html ending for links linking to other lessons on the site. Runs the function in Lesson.js, createMarkup() function.

212 filter .html away from links

---

src/routeObject.js

This should fix the problem where saveURL did not add "/beta" when replacing the URL-state.

Fix for error in the saveURL-function of routeObject

---

src/components/Lesson/Lesson.js
src/components/LevelIcon.js
src/components/Navigation/BreadCrumb.js
src/components/PlaylistPage/LessonItem.js
src/routeObject.js
src/routes-static.js
src/routes.js
src/store.js
src/util.js
webpack.static.config.babel.js

#214 
Adds functionality for showing README-files for lessons in multiple languages. At the moment there is implemented support both for README-files on the form `/README` (the old way) and `/README_(a country's ISO code)` (the new way). For example: `/README_sv` for Swedish. This gives support for having multiple README-files in the same folder, but in different languages. When the old page is taken down, all README-files should be named on the form `/README_(a country's ISO code)`.
A list of new features:
- The veiledning-buttons (renamed to "Lærerveiledning") showing on the PlaylistPage, when in teacher mode, for lessons that has a registered README-file, now links to the coresponding README-file.
- When in teacher mode, there will also be a button with a direct link from a lesson page …

214 veiledning button

---

src/pages/PlaylistPage.js

The course info button added by @krskog accidentally didn't make it into my last PR #239 (see image). I added it back again, adjusted to the new way of displaying the content on the page.

Add back the course info button which was accidentally removed earlier

---

src/components/Navigation/NavBar.js
src/components/Navigation/NavBar.scss
src/index-template.ejs
webpack.config.babel.js

Does 2 things:
1) All use of `:global` should be wrapped by a "local" class when using css-modules. The reason is that if not, it might affect css other places on the page (we are changing global), and also if the global css is loaded first, the specificity of the global space might win. The NavBar was (as far as I coulds see) the only css that used `:global` without a wrapper, so I added this.
2) When injecting `<link>` tags for the extracted css-files, they were inserted after the css `<style>` tags inserted from the isomorphic-style plugin. To fix this, I needed to turn off the automatic injection and "manually" specify in the template where the css should be injected.
These changes will probably only be seen when building and serving the static site.

Fix incorrect serverside styling

---

package.json

Inserted the config of local-web-server in package.json, so that it is possible to just write `ws` in the command line instead of `yarn serve` (both er possible). To see the config, write `ws --config`.
Also removed the `-s index.html`, since it was a bit to eager to redirect to the index.html (it was originally added to simulate the 404-behaviour on github, but it does not behave the same way). Although it is still not like github, it is better.

Simplify yarn serve, adding config of local-web-server in package.json

---

createLessonPdfs.js
lws.config.js
pathlists.js
src/components/Lesson/Lesson.js
src/index-static.js
src/routeObject.js
src/util.js
test/util_spec.js
webpack.config.babel.js
webpack.static.config.babel.js

Solves #386 and https://github.com/kodeklubben/oppgaver/issues/626
Lesson no longer removes html-endings. The router does this in the browser.
Renders static html to e.g. scratch/julekort/julekort.html instead of scratch/julekort/julekort/index.html
Also added rewrite rules to local-web-server so that it understands that `scratch/julekort/julekort` means `scratch/julekort/julekort/index.html` (like github does).

Issue 386 and oppgaverepo issue 626 - redirect html

---

src/components/Filter/FilterGroup.js

Solves #314 
Right now the filter items it's in the same order as it is in keys.md.
But I think everything should be alphabetically except grades. 
Don't know if this is the best way to do it, but it works for every language and it's taken for Mozillas developer site for the sort function
If we don't want this, I think we could just close issue 314

Issue 314 sort filteritems

---

src/components/Lesson/Content.scss

Comment scratchblocks back in. Was commented out in puppeteer PR (#422). Not sure why. Without this, scratchblocks are not rendered.

Comment scratchblocks back in

---

createLessonPdfs.js
lws.config.js
src/html-template.ejs
src/renderStatic.js
webpack.config.babel.js

url_path_prefix aka publicPath aka `/beta` manglet foran css og js-filene i de statisk genererte html-filene etter at vi oppdaterte til webpack 2. Dette skulle fikse det.

Add url_path_prefix (aka publicPath) in statically rendered html-files

---

src/components/Filter/ClearFilterButton.js
src/components/Filter/RadioButtons.js
src/components/Navigation/LanguageDropdown.js
src/reducers/filter.js
src/store.js
test/reducers/filter_spec.js

Solves issue #472 
Also, tries to reduce the amount of filter resetting.
Also, don't reset filter when changing language (except for the language filter).
It still resets filter when change radiobuttons, since playlists still depend on the filter on the course page.

Make sure language is set correctly when updating from localstorage.

---

src/components/CourseList/CourseItem.js
src/components/Filter/LessonFilter.js
src/selectors/playlist.js

Fant en liten bug der antall oppgaver ble borte fra CourseItem. Hvis jeg f.eks. gikk fra norsk til engelsk, for hovedspråk, og jeg hadde tidligere huket av for Oppgavesamlinger på norsk, så endret filteret seg riktig, men antall oppgaver var fortsatt ikke synlig

Antall oppgaver for CourseItem

---

createLessonPdfs.js

Had to change the string the builder was searching for to check that the local server is up, since we switched from local-web-server to express.

Fix pdf-builder

---

buildconstants.js
package.json
src/contexts.js
src/selectors/course.js
src/selectors/frontmatter.js
src/util.js
webpack.config.babel.js
yarn.lock

Update to get tags from data.yml instead of the frontmatter of courses and lessons.
This is needed when https://github.com/kodeklubben/oppgaver/pull/656 is merged.

Get tags from data.yml

---

.eslintrc
package.json
src/components/CourseList/CourseItem.js
src/components/Filter/FilterGroup.js
src/components/Filter/FilterItem.js
src/components/Filter/RadioButtons.js
src/components/FrontPage/TeacherInfobox.js
src/components/InstructionButton.js
src/components/Lesson/MainLanguageButton.js
src/components/Lesson/PdfButton.js
src/components/Lesson/ResetButton.js
src/components/LevelIcon.js
src/components/Navigation/BreadCrumb.js
src/components/Navigation/Footer.js
src/components/Navigation/LanguageDropdown.js
src/components/Navigation/NavBar.js
src/components/PdfHeader.js
src/components/PlaylistPage/LessonItem.js
src/constants/captions_da.js
src/constants/captions_en.js
src/constants/captions_nb.js
src/constants/captions_nn.js
src/constants/captions_sv.js
src/processContent.js
yarn.lock

Solves #465 for this repo. Rest has to be done at the oppgave repo.
img tags is now instead Image components from react-bootstrap. The alt attributes should maybe be a bit better than they are now?
Also added the jsx-a11y plugin for eslint with the recommended rules. This gave 3 more errors including the img alt error. That's why I changed FilterGroup.js, FilterItem.js and RadioButtons.js. This fix is just for the eslinter, but should be further fixed since this is not 100% correct...

Issue 465 Add alt to images

---

src/components/Lesson/ImprovePage.js

Solves #395 
Since we will be releasing the new sites asap, there is no need to do more than just remove the beta from the link. And the link without beta will still show the same lesson, just on the old site

Issue 395 removed beta from link

---

package.json
webpack.config.babel.js
yarn.lock

Don't see any difference with this plugin, other than adding more of the same id's as the children. And this is a bad thing for accessibility

Remove markdown-it-anchor

---

webpack.config.babel.js

For some reason, using pure_funcs=console.log in uglifyjs plugin webpack seems to break the site.

Remove pure_funcs in uglifyjsplugin (webpack)

---

package.json
src/components/LessonPage/PdfButton.js
src/resources/courseFrontmatter.js
src/resources/lessonFrontmatter.js
src/util.js
webpack.config.babel.js

Fixes path to PDF.
Fixes path to images in lesson tooltips.
It also fixes the history-api-fallback when running `yarn start` if `url-path-prefix.config` contains `beta`, so that if you write `.../beta/scratch`, that actually works.

Fix pdf and tooltips

---

createLessonPdfs.js
package.json
pathlists.js
server.js
yarn.lock

Make createLessonPdfs.js more robust and upgrade puppeteer to latest version.
If a PDF-rendering fails, it can retry 3 times. Otherwise, the whole build now fails.

Make createLessonPdfs.js more robust

---

src/components/CoursePage/LessonItem.js
src/components/Navigation/BreadCrumb.js
src/pages/LessonPage.js
src/resources/lessonFrontmatter.js
src/resources/lessons.js

Some places in the code still got `level` from the lesson frontmatter. This has now been fixed.
Also, a warning message is emitted to console if a lesson is missing a level.

Only get level from lesson.yml files.

---

src/components/CourseList/CourseItem.js
src/components/CoursePage/LessonItem.js
src/components/FrontPage/TeacherInfobox.js
src/components/LessonPage/ImprovePage.js
src/components/Navigation/Footer.js
src/pages/LessonPage.js

Lighthouse says it's bad practice to not have rel='noopener' for anchors with target='_blank'

Add rel noopener to links to others sites

---

src/components/LessonPage/Content.scss

When it had display: none it wasn't possible to tab to it. Now I moved the checkbox to the right place and it looks good with a screen reader

Tab through checkboxes

---

src/components/Navigation/NavBar.scss

Remove 2px of shadow below navbar. It used to be 5px. Not sure why it was 5px before, and not sure why it is 7px now.

Remove 2px of shadow below navbar

---

server.js
src/routes.js

Solves #529.
**UPDATE**: Note that instead of adding the redirect from `scratch/` to `scratch/index`, we could add two extra routes like so:
```
const routes =
<Route path="/" component={App} onEnter={appOnEnter} onChange={appOnChange}>
<IndexRoute component={FrontPage}/>
<Route path="/:a/" component={PageNotFound}/>
<Route path="/:course" getComponent={getCoursePage}/>
<Route path="/:a/:b/:c/" component={PageNotFound}/>
<Route path="/:course/:lesson/:file" getComponent={getLessonPage}/>
<Route path="*" component={PageNotFound}/>
</Route>;
```
This will make sure that paths ending in slash are routed to PageNotFound. Note that the params in the route cannot be `course`, `lesson`, and `file` since then the breadcrumb would pick up on them (unless we want that). Here I just used `a`, `b`, …

529 url ends with slash breaks

---

src/resources/lessonFrontmatter.js
src/resources/lessons.js

Helps solve https://github.com/kodeklubben/codeclub-viewer/issues/529
When reading frontmatter, check that lesson.yml exists, otherwise emit a warning.

Check that lesson.yml exists

---

.travis.yml
src/assets/deploy/README.md
src/assets/deploy/google91a144a83c954edb.html
webpack.config.babel.js

Add extra files needed for deploy, and ignore yml-files as resources. Also, only deploy when pushing to non-fork (kodeklubben/codeclub-viewer).
It will still only deploy to norwegiankiwi/kodeklubben.github.io.

Extra files, no copy of yml, only deploy for push to kodeklubben

---

.travis.yml

Deploy to kodeklubben/kodeklubben.github.io instead of norwegiankiwi/kodeklubben.github.io
When/if this PR is merged, anytime a merge is done into kodeklubben/codeclub-viewer's master branch, a new deploy will be made to kodeklubben/kodeklubben.github.io.
It has been tested a little bit first deploying to norwegiankiwi/kodeklubben.github.io, and that seems to work ok.
If this works fine, we can consider adding a similar script to merges on kodeklubben/oppgaver.

Automatic deploy to kodeklubben/kodeklubben.github.io

---

.eslintrc
package.json
yarn.lock

Add eslint-babel-plugin and enable semi, to also catch missing semi-colons in class properties.

Add eslint-babel-plugin

---

src/components/CoursePage/LessonItem.js
src/components/LessonPage/Content.js
src/components/LessonPage/Progress.js
src/pages/LessonPage.js
src/selectors/checkboxes.js
test/reducers/checkboxes_spec.js
test/selectors/checkboxes_spec.js

Note that in Content, we now only update checkboxes once after it is hydrated, not each time (like it was done in LessonPage before).
In addition, moved stuff into pages where they belong.

Refactor LessonPage ++

---

src/components/LessonPage/Content.js
src/components/LessonPage/Content.scss

This PR fixes the problem in issue #654 that checkboxes disappear from filter after visiting a lesson.
The fix is to wrap css for lesson content in classname `.lessonContent` and apply this to the content div.
Note that this might be a symptom that the styles are not being applied correctly. In theory, the css from the lesson page should be removed when moving back to front page or course page.
Tip: When reviewing this, select "Hide whitespace changes"

654: Fix filter checkboxes

---

.travis.yml

Also, change all keywords from dash to underscore, as shown in the documentation.
It seems like dash also works, but that might change in the future. In any case, might as well have the same as they have in the docs.
This commits also moves git config diff.renameLimit to before_deploy, and comments it out. If it doesn't work without it, uncomment it.

Change fqdn to beta.oppgaver.kidsakoder.no (CNAME)

---

src/components/LessonPage/Content.scss

Se #688 - here is a PR to fix that.

Override bootstrap print stylesheet to restore color decorations in print

---

src/components/LessonPage/Content.scss

Because of bootstrap overrides, we need !important for getting more styling when creating PDF or printing

Add !important to styling for rest of content css
